# keeping this pipeline for now to get Microsoft.MLOpsPython working on https://dev.azure.com/customai/DevopsForAI-AML
pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: AzureKeyVaultSecrets

trigger:
- master
- releases/*
- develop

steps:
- script: | 
   echo 'dummy step'
   
  displayName: 'Dummy step'

