resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

trigger:
  branches:
    include:
    - master

  paths:
    include:
    - environment_setup/*

variables:
  containerRegistry: $[coalesce(variables['acrServiceConnection'], 'acrconnection')]
<<<<<<< HEAD
  imageName: $[coalesce(variables['agentImageName'], 'public/mlops/mlopspython')]  
=======
  imageName: $[coalesce(variables['imageName'], 'public/mlops/mlopspython')]  
>>>>>>> 176319a31930500d855b0a1183f32de2c567ce07

steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageName)'
      tags: 'latest'
      buildContext: '$(Build.SourcesDirectory)' 
      dockerFile: '$(Build.SourcesDirectory)/environment_setup/Dockerfile'
