resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

trigger:
  branches:
    include:
    - master

  paths:
    include:
    - environment_setup/*

steps:

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: msftDockerHub

- task: Docker@2
  displayName: 'Build and push an image'
  inputs:
    command: buildAndPush
    repository: dtzar/conda3mlops
    buildContext: '$(Build.SourcesDirectory)/environment_setup'
    tags: |
      $(Build.BuildNumber)
      latest