pr: none
trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'


container:
  image: pepsimlamlcr.azurecr.io/mlopsbuildagent:latest
  endpoint: acrbackupconnection


variables:
  SOURCES_DIR: $[coalesce(variables['SOURCES_DIR_OVERRIDE'], '$(Build.SourcesDirectory)/Code/src/train')]
  TRAIN_SCRIPT_PATH: $[coalesce(variables['TRAIN_SCRIPT_PATH_OVERRIDE'], 'src/train/train.py')]


steps:
- bash: |
   # Invoke the Python training pipeline
   echo $SP_APP_SECRET   
   #python3 $(Build.SourcesDirectory)/aml_pipelines/model_train_pipeline.py
  failOnStderr: 'false'
  env:
    SOURCES_DIR: '$(Build.SourcesDirectory)'
    SP_APP_SECRET: $(SP_APP_SECRET)
    BLOB_STORAGE_Key: '$(BLOB_STORAGE_Key)'
  displayName: 'Train model using AML with Remote Compute'
  enabled: 'true'