pr: none
trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: pepsimlamlcr.azurecr.io/mlopsbuildagent:latest
  endpoint: acrbackupconnection


variables:
- group: devopsforai-aml-vg


steps:
- bash: |
   # Invoke the Python training pipeline
   python3 $(Build.SourcesDirectory)/aml_pipelines/model_train_pipeline.py
  failOnStderr: 'false'
  env:
    BLOB_STORAGE_Key: '$(BLOB_STORAGE_Key)'
    SP_APP_SECRET: '$(SP_APP_SECRET)'
  displayName: 'Train model using AML with Remote Compute'
  enabled: 'true'